#!/usr/bin/env python
"""
extracts information from slp files such as node coordinates.
"""
import os
import sys

import numpy
import pandas
import sleap_io
from logging_config import get_logger

logger = get_logger(__name__)


class SleapParser:
    """
    Parses the information out of the .slp files generated by SLEAP_model.py and saves the data as a csv file
    """

    def __init__(self, slp_file):
        self.slp_file = slp_file

    def create_dataframe(self, node_names):
        """
        creates an empty pandas dataframe for sleap_to_csv to fill
        :param node_names: list with strings
        :return: empty pandas dataframe
        """

        logger.debug("Making data frame...")
        # make list with standard SLEAP data
        sleap_video_datatypes = [("video", str), ("video_height", int), ("video_width", int),
                                 ("frame_idx", int), ("fps", int), ("instance_id", int),
                                 ("instance_score", int)]
        # add nodes from the skeleton used in de video
        for name in node_names:
            # set x and y coordinates
            name_x = name + "_x"
            name_y = name + "_y"
            sleap_video_datatypes.append((name_x, int))
            sleap_video_datatypes.append((name_y, int))
        data_types = numpy.dtype(sleap_video_datatypes)
        # make empty pandas data frame
        data_frame = pandas.DataFrame(numpy.empty(0, dtype=data_types))
        return data_frame

    def sleap_to_csv(self, filename):
        """
        Loads data from a .slp file (sleap) into a pandas data frame and saves it as a csv
        """
        logger.info(f"Loading SLEAP file: {filename}")
        # load SLEAP (.slp) file
        labels = sleap_io.load_file(filename)
        # get video name for dataframe csv
        file_path = labels.video.backend.filename
        video_name = os.path.splitext(os.path.basename(filename))[0]
        # get node names from skeleton
        node_names = labels.skeleton.node_names

        # get video shape
        (video_frame_count, video_height, video_width, c) = labels.video.shape
        logger.debug(f"frame count video: {video_frame_count}")
        # get frames per second
        fps = getattr(labels.video.backend, "fps", None)

        # make empty data frame
        data_frame = self.create_dataframe(node_names)

        logger.info(f"Converting {video_name}.slp to CSV...")
        for frame in labels.labeled_frames:
            frame_id = frame.frame_idx

            for count, instance in enumerate(frame.predicted_instances):
                node_points = instance.points
                score = instance.score
                # make a new row for data frame
                new_row = {"video": file_path, "frame_idx": frame_id, "instance_id": count,
                           "instance_score": score, "video_height": video_height,
                           "video_width": video_width, "fps": fps}
                
                for point in node_points:
                    # get name of node
                    node_name = point[4]
                    # get PredictedPoint object
                    p_point = point[0]
                    # get coordinates form predictedPoint object
                    tuple_point = tuple(p_point)

                    x, y = tuple_point[:2]
                    node_name_x = node_name + "_x"
                    node_name_y = node_name + "_y"
                    # save coordinates in new_row
                    new_row[node_name_x] = [x]
                    new_row[node_name_y] = [y]
                    # save scores of every point in new row
                    node_name_score = f"{node_name}_score"
                    point_score = point[1]
                    new_row[node_name_score] = [point_score]
                df1 = pandas.DataFrame(new_row)
                data_frame = pandas.concat([data_frame, df1], ignore_index=True)
        # change extension for file name
        # save to csv
        csv_path = os.path.join(os.path.dirname(filename), f"{video_name}.csv")
        data_frame.to_csv(csv_path, index=False)
        logger.info(f"CSV file saved to: {csv_path}")


def main():
    from logging_config import setup_logging
    setup_logging()
    logger.info("Starting SLEAP_parser test")
    sp = SleapParser(r"C:\Users\avanderleij\OneDrive - NIOZ\Bureaublad\Explortation_Test_sleap\2018-09-12\F02_2018-09-18_Z083970.slp")
    sp.sleap_to_csv(r"C:\Users\avanderleij\OneDrive - NIOZ\Bureaublad\Explortation_Test_sleap\2018-09-12\F02_2018-09-18_Z083970.slp")


if __name__ == "__main__":
    sys.exit(main())
