#!/usr/bin/env python
"""
extracts information from slp files such as node coordinates.
"""
import os
import sys

import numpy as np
from PIL import Image
import pandas
import sleap_io
from logging_config import get_logger

logger = get_logger(__name__)


class SleapParser:
    """
    Parses the information out of the .slp files generated by SLEAP_model.py and saves the data as a csv file
    """

    def __init__(self, slp_file):
        self.labels = self.load_labels(slp_file)

    def create_dataframe(self, node_names):
        """
        creates an empty pandas dataframe for sleap_to_csv to fill
        :param node_names: list with strings
        :return: empty pandas dataframe
        """

        logger.debug("Making data frame...")
        # make list with standard SLEAP data
        sleap_video_datatypes = [("video", str), ("video_height", int), ("video_width", int),
                                 ("frame_idx", int), ("fps", int), ("instance_id", int),
                                 ("instance_score", int)]
        # add nodes from the skeleton used in de video
        for name in node_names:
            # set x and y coordinates
            name_x = name + "_x"
            name_y = name + "_y"
            sleap_video_datatypes.append((name_x, int))
            sleap_video_datatypes.append((name_y, int))
        data_types = np.dtype(sleap_video_datatypes)
        # make empty pandas data frame
        data_frame = pandas.DataFrame(np.empty(0, dtype=data_types))
        return data_frame

    def load_labels(self, filename):
        logger.info(f"Loading SLEAP file: {filename}")
        # load SLEAP (.slp) file
        labels = sleap_io.load_file(filename)
        # set labels

        return labels


    def sleap_to_csv(self, filename):
        """
        Loads data from a .slp file (sleap) into a pandas data frame and saves it as a csv
        """
        # get video name for dataframe csv
        file_path = self.labels.video.backend.filename
        video_name = os.path.splitext(os.path.basename(filename))[0]
        # get node names from skeleton
        node_names = self.labels.skeleton.node_names

        # get video shape
        (video_frame_count, video_height, video_width, c) = self.labels.video.shape
        n_labeled_frames = len(self.labels.labeled_frames)
        logger.debug(f"frame count video: {video_frame_count}")
        logger.debug(f"{n_labeled_frames} of video frames have labels")
        logger.info(f"{100 * n_labeled_frames / video_frame_count:.2f}% of frames are labeled")

        # get frames per second
        fps = getattr(self.labels.video.backend, "fps", None)

        # make empty data frame
        data_frame = self.create_dataframe(node_names)

        logger.info(f"Converting {video_name}.slp to CSV...")
        for frame in self.labels.labeled_frames:
            frame_id = frame.frame_idx

            for count, instance in enumerate(frame.predicted_instances):
                node_points = instance.points
                score = instance.score
                # make a new row for data frame
                new_row = {"video": file_path, "frame_idx": frame_id, "instance_id": count,
                           "instance_score": score, "video_height": video_height,
                           "video_width": video_width, "fps": fps}
                
                for point in node_points:
                    # get name of node
                    node_name = point[4]
                    # get PredictedPoint object
                    p_point = point[0]
                    # get coordinates form predictedPoint object
                    tuple_point = tuple(p_point)

                    x, y = tuple_point[:2]
                    node_name_x = node_name + "_x"
                    node_name_y = node_name + "_y"
                    # save coordinates in new_row
                    new_row[node_name_x] = [x]
                    new_row[node_name_y] = [y]
                    # save scores of every point in new row
                    node_name_score = f"{node_name}_score"
                    point_score = point[1]
                    new_row[node_name_score] = [point_score]
                df1 = pandas.DataFrame(new_row)
                data_frame = pandas.concat([data_frame, df1], ignore_index=True)
        # change extension for file name
        # save to csv
        csv_path = os.path.join(os.path.dirname(filename), f"{video_name}.csv")
        data_frame.to_csv(csv_path, index=False)
        logger.info(f"CSV file saved to: {csv_path}")


    def render_image(self):
        # n_label_frames = len(self.labels.labeled_frames)
        # if n_label_frames == 0:
        #     return []

        # # Get 4 evenly spaced indices frames
        # frame_indices = np.linspace(0, n_label_frames - 1, num=4, dtype=int)

        # frames = []
        # for i in frame_indices:
        #     img = sleap_io.render_image(self.labels.labeled_frames[int(i)], color_by="instance",)
        #     frames.append(img)

        # montage = np.concatenate(frames, axis=1)
        # montage = Image.fromarray(montage)
        # montage.show()
        sleap_io.render_video(self.labels, "output.mp4")
        return 0

    def parse_results(self, file_name):

        self.sleap_to_csv(filename=file_name)
        self.render_image()


def main():
    from logging_config import setup_logging
    setup_logging()
    logger.info("Starting SLEAP_parser test")

if __name__ == "__main__":
    sys.exit(main())
